# Generated by Django 5.2.1 on 2025-05-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("availability", models.JSONField()),
                ("params", models.JSONField()),
                ("student_id", models.CharField(max_length=100)),
                ("schedule", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SavedSchedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedules", models.JSONField()),
            ],
        ),
    ]
