# Generated by Django 5.2.1 on 2025-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
